### ISSUE TITLE
1주차 알고리즘 문제 추가

### ISSUE THREAD

**Issue by jayden-lee** [weggdul/algorithm#1]
- 문제 1094번 막대기, 1085번 직사각형에서 탈출

**Comment by weduls** [comment]
주에 두 문제는 타임라인 이슈도 해야해서 좀 많은거 같은데 한문제 어떤가요

**Comment by jayden-lee** [comment]
> 주에 두 문제는 타임라인 이슈도 해야해서 좀 많은거 같은데 한문제 어떤가요

이번주(8월8일까지)는 그럼 1094번 막대기 문제만 푸는걸로 해요
