### ISSUE TITLE
알고리즘 문제 풀이 사이트 변경

### ISSUE THREAD

**Issue by jayden-lee** [weggdul/algorithm#2]
## 알고리즘 문제 풀이 사이트

1. https://www.codility.com/
2. https://leetcode.com/
3. https://www.acmicpc.net/ (기존)

@weduls 기존에 이용하던 사이트를 유지할지 아니면 다른 사이트로 변경하는 것이 좋을지 답변주세요 ❓

**Comment by jayden-lee** [comment]
https://leetcode.com 으로 변경하기로 결정

**Comment by weduls** [comment]
누구마음대루

**Comment by jayden-lee** [comment]
@weduls 슬랙으로 이야기한거 아니였나? 그럼 바꾸지말까?
